### ISSUE TITLE
React Grid Virtual Scrolling scroll performance

### ISSUE THREAD

**Issue by veznidav** [DevExpress/devextreme-reactive#1200]
I use React Grid with virtual scrolling. The grid has about 500 rows. I test the application on multiple mobile devices and some of them have problems with performance. On some devices scrolling through the items is laggy exactly like in this article (17.2 version): https://community.devexpress.com/blogs/javascript/archive/2018/05/16/datagrid-and-treelist-performance-improvements-v18-1.aspx  
I use these packages: 
` "@devexpress/dx-grid-core": "^1.1.2"`
`"@devexpress/dx-react-core": "^1.1.2"`
`"@devexpress/dx-react-grid": "^1.1.2"`
`"@devexpress/dx-react-grid-material-ui": "^1.1.2"`

Is the improvement that is mentioned in the article above already included in these versions?  Is there any other solution how to deal with laggy scrolling?

**Comment by kvet** [comment]
Hi,

This blog post is not related to the DevExtreme Reactive project. However, we've released column virtualization support in the 1.2.0 release. It improves performance on mobile devices, especially with the big amount of columns.

**Comment by veznidav** [comment]
Thank you for your reply. But it is only associated with columns, not with rows, correct? And one more question - is there a possibility how to show "dummy rows" (just rows with some placeholder) when scrolling through "not yet generated" rows? These rows become regular rows when they are fully loaded. Users will know that something should appear.

**Comment by kvet** [comment]
Yes, the change is only in column rendering. Row rendering has been optimized from the very first release. You can check the following library that implements virtual scrolling: https://bvaughn.github.io/react-virtualized/#/components/Table. If it performs a way better on your device, please let us know.
 
I am afraid VirtualTable doesn't notify users of changing visible rows and columns. You can create a separate issue with a feature request for such a functionality.

**Comment by RahavLussato** [comment]
hi @kvet i can say that for me react-virtualized works much faster even after the columns virtualization you added which made it a bit faster but still not fast as react-virtualized.
if i need to guess what is the reason it can be one of 2:
1. react-virtualized might implemented the row virtualization in a different way.
2. there is a lot of paint performence warnings when scrolling from chrome such as "[Violation] Forced reflow while executing JavaScript" and "[Violation] 'scroll' handler" "[Violation] 'message' handler"
