### ISSUE TITLE
How to move TableEditColumn commands into a context menu

### ISSUE THREAD

**Issue by vtrphan** [DevExpress/devextreme-reactive#3205]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I'd like to move the edit and delete commands in the TableEditColumn into a context menu to save space. How can i do this? 

- devextreme-reactive: 2.7.3
- react: latest
- browser: latest
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by ismailat** [comment]
I wanted to do this as well. The only alternative I found is using this [example](https://codesandbox.io/s/2qloh). It doesn't have the delete button but you should be able to add it yourself inside the editing zone. Hope it helps!

**Comment by vtrphan** [comment]
The edit button in that example is actually the expand detail section button in disguise. Unfortunately it doesn't help me further because i want to move the edit/delete command in the EditColumn into a context menu, i.e  user click on a button and a menu appear with edit/delete command, which will save some space in the table.
I have already implemented the context menu. I just don't know how to trigger the Edit process with my custom button. There is an example about how to change the icons for those buttons but that's it.

**Comment by ismailat** [comment]
I see, then you want a different solution. I currently don't know how to do that modification but I would recommend checking the props for TableEditColumn in the docs and then check the children of the Cell and and Edit components used. Maybe you missed to implement the default function that executes once you click the button. Try to do it on a sandbox and post it here, someone else could help you with it.

**Comment by LazyLahtak** [comment]
Hi @vtrphan,

I suggest that you customize the [TableEditColumn.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumncellprops) component. Here is an [example](https://codesandbox.io/s/winter-brook-nzthz). For this, I used [Material-UI Menu](https://material-ui.com/ru/components/menus/). Also, I removed padding from the [TableEditColumn.HeaderCell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumnheadercellprops) component and defined the `width` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#properties).

If you have any further questions, feel free to contact us.
